[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
fulltime = "2MzYe6Zo4AD2fuszYou7CcnVmo7cdq4WjKi8UERL652L"

[provider]
cluster = "devnet"
wallet = ".keys/dev-wallet.json"

[scripts]
test = "cargo test"

[hooks]
